apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-factory-pvc
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-factory-logs-pvc
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-factory-embeddings-pvc
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    component: embeddings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-premium